### ISSUE TITLE
autolabor_pro1运行出错

### ISSUE THREAD

**Issue by ghost** [kinglintianxia/autolabor_pro1#1]
您好，我在按照readme过程运行的时候，有一些小问题，具体如下：
(*)在机器人运动规划部分的move_base测试部分，执行roslaunch autolabor_pro1_nav auto_move_base_blank_map.launch后，rviz中
RobotModel的Status显示Error，其中URDF是正确，但是下面的提示No transform from [] to [map]
以及LaserScan提示Transform [sender=unknown_publisher]
For frame [laser]: Frame [laser] does not exist
和Axes提示都是Error

**Comment by kinglintianxia** [comment]
你好，机器人URDF模型的链接关系是：
```
root Link: base_footprint has 1 child(ren)
    child(1):  base_link
        child(1):  base_l1_wheel_link
        child(2):  base_l2_wheel_link
        child(3):  base_laser_bottom
            child(1):  base_laser_middle
                child(1):  base_laser
        child(4):  base_r1_wheel_link
        child(5):  base_r2_wheel_link
```
你查看雷达的Frame是不是`base_laser`，要和URDF保持一致。你可以单独启动机器人模型看看是否出错，单独启动雷达节点看是否正常。能否给出错截图看看。
