### ISSUE TITLE
tf error: Could not find a connection between 'map' and 'base_footprint' because they are not part of the same tree.Tf has two or more unconnected trees.

### ISSUE THREAD

**Issue by ghost** [kinglintianxia/autolabor_pro1#2]
在运行move_base测试的时候，可以gmapping建图的时候都会提示tf error: Could not find a connection between 'map' and 'base_footprint' （也有其他模块）because they are not part of the same tree.Tf has two or more unconnected trees.请问怎么解决呢？感激不尽！

**Comment by kinglintianxia** [comment]
你好，你这个错误提示tf trees有问题，tf变换树断开了。你可以运行：
```shell
$ rosrun rqt_tf_tree rqt_tf_tree
```
查看ROS TF frame tree。
gmapping建图有专用的启动文件：
```shell
$ roslaunch autolabor_pro1_nav auto_gmapping.launch
```

**Comment by IamLee456** [comment]
在 rplidar.launch 文件的最后加上这样一段代码：
<node name = "foot_to_map" pkg = "tf" type = "static_transform_publisher" args = "0.0 0.0 0.18 3.14 3.14 0.0 base_footprint map 100" />
可以解决

**Comment by IamLee456** [comment]
在   rplidar.launch 文件的最后加上这样一段代码：
<node name = "foot_to_map" pkg = "tf" type = "static_transform_publisher" args = "0.0 0.0 0.18 3.14 3.14 0.0 base_footprint map 100" />

**Comment by ghost** [comment]
您好，经过这段时间的调试，发现您autolabor_nav_driver文件夹下的driver.launch中的base_frame没有改为base_footprint导致的这个问题

**Comment by kinglintianxia** [comment]
好的，我晚上看看，谢谢😜发自我的华为手机
